/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as LandingAuthRouteImport } from './routes/_landing/auth'
import { Route as ProtectedUserIndexRouteImport } from './routes/_protected/user/index'
import { Route as ProtectedOrgIndexRouteImport } from './routes/_protected/org/index'
import { Route as ApiPollGenerateQuestionsRouteImport } from './routes/api/poll/generate-questions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedUserNewRouteImport } from './routes/_protected/user/new'
import { Route as ProtectedUserMeRouteImport } from './routes/_protected/user/me'
import { Route as ProtectedUserIdRouteImport } from './routes/_protected/user/$id'
import { Route as ProtectedPollNewRouteImport } from './routes/_protected/poll/new'
import { Route as ProtectedPollImportRouteImport } from './routes/_protected/poll/import'
import { Route as ProtectedOrgNewRouteImport } from './routes/_protected/org/new'
import { Route as ProtectedOrgOrgSlugIndexRouteImport } from './routes/_protected/org/$orgSlug/index'
import { Route as LandingPollSlugIndexRouteImport } from './routes/_landing/poll/$slug/index'
import { Route as ProtectedUserUpdateIdRouteImport } from './routes/_protected/user/update.$id'
import { Route as ProtectedPollSlugUserResultRouteImport } from './routes/_protected/poll/$slug.user-result'
import { Route as ProtectedPollSlugUpdateRouteImport } from './routes/_protected/poll/$slug.update'
import { Route as ProtectedOrgOrgSlugMembersRouteImport } from './routes/_protected/org/$orgSlug/members'
import { Route as ProtectedOrgOrgSlugInviteRouteImport } from './routes/_protected/org/$orgSlug/invite'
import { Route as LandingPollSlugResultRouteImport } from './routes/_landing/poll/$slug/result'
import { Route as LandingPollSlugPasswordRouteImport } from './routes/_landing/poll/$slug/password'
import { Route as ProtectedOrgOrgSlugPollsNewRouteImport } from './routes/_protected/org/$orgSlug/polls.new'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const LandingAuthRoute = LandingAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => LandingRoute,
} as any)
const ProtectedUserIndexRoute = ProtectedUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgIndexRoute = ProtectedOrgIndexRouteImport.update({
  id: '/org/',
  path: '/org/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiPollGenerateQuestionsRoute =
  ApiPollGenerateQuestionsRouteImport.update({
    id: '/api/poll/generate-questions',
    path: '/api/poll/generate-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUserNewRoute = ProtectedUserNewRouteImport.update({
  id: '/user/new',
  path: '/user/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUserMeRoute = ProtectedUserMeRouteImport.update({
  id: '/user/me',
  path: '/user/me',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUserIdRoute = ProtectedUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPollNewRoute = ProtectedPollNewRouteImport.update({
  id: '/poll/new',
  path: '/poll/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPollImportRoute = ProtectedPollImportRouteImport.update({
  id: '/poll/import',
  path: '/poll/import',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgNewRoute = ProtectedOrgNewRouteImport.update({
  id: '/org/new',
  path: '/org/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgOrgSlugIndexRoute =
  ProtectedOrgOrgSlugIndexRouteImport.update({
    id: '/org/$orgSlug/',
    path: '/org/$orgSlug/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const LandingPollSlugIndexRoute = LandingPollSlugIndexRouteImport.update({
  id: '/poll/$slug/',
  path: '/poll/$slug/',
  getParentRoute: () => LandingRoute,
} as any)
const ProtectedUserUpdateIdRoute = ProtectedUserUpdateIdRouteImport.update({
  id: '/user/update/$id',
  path: '/user/update/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPollSlugUserResultRoute =
  ProtectedPollSlugUserResultRouteImport.update({
    id: '/poll/$slug/user-result',
    path: '/poll/$slug/user-result',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPollSlugUpdateRoute = ProtectedPollSlugUpdateRouteImport.update({
  id: '/poll/$slug/update',
  path: '/poll/$slug/update',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgOrgSlugMembersRoute =
  ProtectedOrgOrgSlugMembersRouteImport.update({
    id: '/org/$orgSlug/members',
    path: '/org/$orgSlug/members',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrgOrgSlugInviteRoute =
  ProtectedOrgOrgSlugInviteRouteImport.update({
    id: '/org/$orgSlug/invite',
    path: '/org/$orgSlug/invite',
    getParentRoute: () => ProtectedRoute,
  } as any)
const LandingPollSlugResultRoute = LandingPollSlugResultRouteImport.update({
  id: '/poll/$slug/result',
  path: '/poll/$slug/result',
  getParentRoute: () => LandingRoute,
} as any)
const LandingPollSlugPasswordRoute = LandingPollSlugPasswordRouteImport.update({
  id: '/poll/$slug/password',
  path: '/poll/$slug/password',
  getParentRoute: () => LandingRoute,
} as any)
const ProtectedOrgOrgSlugPollsNewRoute =
  ProtectedOrgOrgSlugPollsNewRouteImport.update({
    id: '/org/$orgSlug/polls/new',
    path: '/org/$orgSlug/polls/new',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof LandingAuthRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/org/new': typeof ProtectedOrgNewRoute
  '/poll/import': typeof ProtectedPollImportRoute
  '/poll/new': typeof ProtectedPollNewRoute
  '/user/$id': typeof ProtectedUserIdRoute
  '/user/me': typeof ProtectedUserMeRoute
  '/user/new': typeof ProtectedUserNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/poll/generate-questions': typeof ApiPollGenerateQuestionsRoute
  '/org/': typeof ProtectedOrgIndexRoute
  '/user/': typeof ProtectedUserIndexRoute
  '/poll/$slug/password': typeof LandingPollSlugPasswordRoute
  '/poll/$slug/result': typeof LandingPollSlugResultRoute
  '/org/$orgSlug/invite': typeof ProtectedOrgOrgSlugInviteRoute
  '/org/$orgSlug/members': typeof ProtectedOrgOrgSlugMembersRoute
  '/poll/$slug/update': typeof ProtectedPollSlugUpdateRoute
  '/poll/$slug/user-result': typeof ProtectedPollSlugUserResultRoute
  '/user/update/$id': typeof ProtectedUserUpdateIdRoute
  '/poll/$slug/': typeof LandingPollSlugIndexRoute
  '/org/$orgSlug/': typeof ProtectedOrgOrgSlugIndexRoute
  '/org/$orgSlug/polls/new': typeof ProtectedOrgOrgSlugPollsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof LandingAuthRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/org/new': typeof ProtectedOrgNewRoute
  '/poll/import': typeof ProtectedPollImportRoute
  '/poll/new': typeof ProtectedPollNewRoute
  '/user/$id': typeof ProtectedUserIdRoute
  '/user/me': typeof ProtectedUserMeRoute
  '/user/new': typeof ProtectedUserNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/poll/generate-questions': typeof ApiPollGenerateQuestionsRoute
  '/org': typeof ProtectedOrgIndexRoute
  '/user': typeof ProtectedUserIndexRoute
  '/poll/$slug/password': typeof LandingPollSlugPasswordRoute
  '/poll/$slug/result': typeof LandingPollSlugResultRoute
  '/org/$orgSlug/invite': typeof ProtectedOrgOrgSlugInviteRoute
  '/org/$orgSlug/members': typeof ProtectedOrgOrgSlugMembersRoute
  '/poll/$slug/update': typeof ProtectedPollSlugUpdateRoute
  '/poll/$slug/user-result': typeof ProtectedPollSlugUserResultRoute
  '/user/update/$id': typeof ProtectedUserUpdateIdRoute
  '/poll/$slug': typeof LandingPollSlugIndexRoute
  '/org/$orgSlug': typeof ProtectedOrgOrgSlugIndexRoute
  '/org/$orgSlug/polls/new': typeof ProtectedOrgOrgSlugPollsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_landing/auth': typeof LandingAuthRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_landing/': typeof LandingIndexRoute
  '/_protected/org/new': typeof ProtectedOrgNewRoute
  '/_protected/poll/import': typeof ProtectedPollImportRoute
  '/_protected/poll/new': typeof ProtectedPollNewRoute
  '/_protected/user/$id': typeof ProtectedUserIdRoute
  '/_protected/user/me': typeof ProtectedUserMeRoute
  '/_protected/user/new': typeof ProtectedUserNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/poll/generate-questions': typeof ApiPollGenerateQuestionsRoute
  '/_protected/org/': typeof ProtectedOrgIndexRoute
  '/_protected/user/': typeof ProtectedUserIndexRoute
  '/_landing/poll/$slug/password': typeof LandingPollSlugPasswordRoute
  '/_landing/poll/$slug/result': typeof LandingPollSlugResultRoute
  '/_protected/org/$orgSlug/invite': typeof ProtectedOrgOrgSlugInviteRoute
  '/_protected/org/$orgSlug/members': typeof ProtectedOrgOrgSlugMembersRoute
  '/_protected/poll/$slug/update': typeof ProtectedPollSlugUpdateRoute
  '/_protected/poll/$slug/user-result': typeof ProtectedPollSlugUserResultRoute
  '/_protected/user/update/$id': typeof ProtectedUserUpdateIdRoute
  '/_landing/poll/$slug/': typeof LandingPollSlugIndexRoute
  '/_protected/org/$orgSlug/': typeof ProtectedOrgOrgSlugIndexRoute
  '/_protected/org/$orgSlug/polls/new': typeof ProtectedOrgOrgSlugPollsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/org/new'
    | '/poll/import'
    | '/poll/new'
    | '/user/$id'
    | '/user/me'
    | '/user/new'
    | '/api/auth/$'
    | '/api/poll/generate-questions'
    | '/org/'
    | '/user/'
    | '/poll/$slug/password'
    | '/poll/$slug/result'
    | '/org/$orgSlug/invite'
    | '/org/$orgSlug/members'
    | '/poll/$slug/update'
    | '/poll/$slug/user-result'
    | '/user/update/$id'
    | '/poll/$slug/'
    | '/org/$orgSlug/'
    | '/org/$orgSlug/polls/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/org/new'
    | '/poll/import'
    | '/poll/new'
    | '/user/$id'
    | '/user/me'
    | '/user/new'
    | '/api/auth/$'
    | '/api/poll/generate-questions'
    | '/org'
    | '/user'
    | '/poll/$slug/password'
    | '/poll/$slug/result'
    | '/org/$orgSlug/invite'
    | '/org/$orgSlug/members'
    | '/poll/$slug/update'
    | '/poll/$slug/user-result'
    | '/user/update/$id'
    | '/poll/$slug'
    | '/org/$orgSlug'
    | '/org/$orgSlug/polls/new'
  id:
    | '__root__'
    | '/_landing'
    | '/_protected'
    | '/_landing/auth'
    | '/_protected/dashboard'
    | '/_landing/'
    | '/_protected/org/new'
    | '/_protected/poll/import'
    | '/_protected/poll/new'
    | '/_protected/user/$id'
    | '/_protected/user/me'
    | '/_protected/user/new'
    | '/api/auth/$'
    | '/api/poll/generate-questions'
    | '/_protected/org/'
    | '/_protected/user/'
    | '/_landing/poll/$slug/password'
    | '/_landing/poll/$slug/result'
    | '/_protected/org/$orgSlug/invite'
    | '/_protected/org/$orgSlug/members'
    | '/_protected/poll/$slug/update'
    | '/_protected/poll/$slug/user-result'
    | '/_protected/user/update/$id'
    | '/_landing/poll/$slug/'
    | '/_protected/org/$orgSlug/'
    | '/_protected/org/$orgSlug/polls/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPollGenerateQuestionsRoute: typeof ApiPollGenerateQuestionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_landing/auth': {
      id: '/_landing/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof LandingAuthRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_protected/user/': {
      id: '/_protected/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof ProtectedUserIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/org/': {
      id: '/_protected/org/'
      path: '/org'
      fullPath: '/org/'
      preLoaderRoute: typeof ProtectedOrgIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/poll/generate-questions': {
      id: '/api/poll/generate-questions'
      path: '/api/poll/generate-questions'
      fullPath: '/api/poll/generate-questions'
      preLoaderRoute: typeof ApiPollGenerateQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/user/new': {
      id: '/_protected/user/new'
      path: '/user/new'
      fullPath: '/user/new'
      preLoaderRoute: typeof ProtectedUserNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/user/me': {
      id: '/_protected/user/me'
      path: '/user/me'
      fullPath: '/user/me'
      preLoaderRoute: typeof ProtectedUserMeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/user/$id': {
      id: '/_protected/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof ProtectedUserIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/new': {
      id: '/_protected/poll/new'
      path: '/poll/new'
      fullPath: '/poll/new'
      preLoaderRoute: typeof ProtectedPollNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/import': {
      id: '/_protected/poll/import'
      path: '/poll/import'
      fullPath: '/poll/import'
      preLoaderRoute: typeof ProtectedPollImportRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/org/new': {
      id: '/_protected/org/new'
      path: '/org/new'
      fullPath: '/org/new'
      preLoaderRoute: typeof ProtectedOrgNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/org/$orgSlug/': {
      id: '/_protected/org/$orgSlug/'
      path: '/org/$orgSlug'
      fullPath: '/org/$orgSlug/'
      preLoaderRoute: typeof ProtectedOrgOrgSlugIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_landing/poll/$slug/': {
      id: '/_landing/poll/$slug/'
      path: '/poll/$slug'
      fullPath: '/poll/$slug/'
      preLoaderRoute: typeof LandingPollSlugIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_protected/user/update/$id': {
      id: '/_protected/user/update/$id'
      path: '/user/update/$id'
      fullPath: '/user/update/$id'
      preLoaderRoute: typeof ProtectedUserUpdateIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/$slug/user-result': {
      id: '/_protected/poll/$slug/user-result'
      path: '/poll/$slug/user-result'
      fullPath: '/poll/$slug/user-result'
      preLoaderRoute: typeof ProtectedPollSlugUserResultRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/poll/$slug/update': {
      id: '/_protected/poll/$slug/update'
      path: '/poll/$slug/update'
      fullPath: '/poll/$slug/update'
      preLoaderRoute: typeof ProtectedPollSlugUpdateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/org/$orgSlug/members': {
      id: '/_protected/org/$orgSlug/members'
      path: '/org/$orgSlug/members'
      fullPath: '/org/$orgSlug/members'
      preLoaderRoute: typeof ProtectedOrgOrgSlugMembersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/org/$orgSlug/invite': {
      id: '/_protected/org/$orgSlug/invite'
      path: '/org/$orgSlug/invite'
      fullPath: '/org/$orgSlug/invite'
      preLoaderRoute: typeof ProtectedOrgOrgSlugInviteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_landing/poll/$slug/result': {
      id: '/_landing/poll/$slug/result'
      path: '/poll/$slug/result'
      fullPath: '/poll/$slug/result'
      preLoaderRoute: typeof LandingPollSlugResultRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_landing/poll/$slug/password': {
      id: '/_landing/poll/$slug/password'
      path: '/poll/$slug/password'
      fullPath: '/poll/$slug/password'
      preLoaderRoute: typeof LandingPollSlugPasswordRouteImport
      parentRoute: typeof LandingRoute
    }
    '/_protected/org/$orgSlug/polls/new': {
      id: '/_protected/org/$orgSlug/polls/new'
      path: '/org/$orgSlug/polls/new'
      fullPath: '/org/$orgSlug/polls/new'
      preLoaderRoute: typeof ProtectedOrgOrgSlugPollsNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface LandingRouteChildren {
  LandingAuthRoute: typeof LandingAuthRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingPollSlugPasswordRoute: typeof LandingPollSlugPasswordRoute
  LandingPollSlugResultRoute: typeof LandingPollSlugResultRoute
  LandingPollSlugIndexRoute: typeof LandingPollSlugIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingAuthRoute: LandingAuthRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingPollSlugPasswordRoute: LandingPollSlugPasswordRoute,
  LandingPollSlugResultRoute: LandingPollSlugResultRoute,
  LandingPollSlugIndexRoute: LandingPollSlugIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedOrgNewRoute: typeof ProtectedOrgNewRoute
  ProtectedPollImportRoute: typeof ProtectedPollImportRoute
  ProtectedPollNewRoute: typeof ProtectedPollNewRoute
  ProtectedUserIdRoute: typeof ProtectedUserIdRoute
  ProtectedUserMeRoute: typeof ProtectedUserMeRoute
  ProtectedUserNewRoute: typeof ProtectedUserNewRoute
  ProtectedOrgIndexRoute: typeof ProtectedOrgIndexRoute
  ProtectedUserIndexRoute: typeof ProtectedUserIndexRoute
  ProtectedOrgOrgSlugInviteRoute: typeof ProtectedOrgOrgSlugInviteRoute
  ProtectedOrgOrgSlugMembersRoute: typeof ProtectedOrgOrgSlugMembersRoute
  ProtectedPollSlugUpdateRoute: typeof ProtectedPollSlugUpdateRoute
  ProtectedPollSlugUserResultRoute: typeof ProtectedPollSlugUserResultRoute
  ProtectedUserUpdateIdRoute: typeof ProtectedUserUpdateIdRoute
  ProtectedOrgOrgSlugIndexRoute: typeof ProtectedOrgOrgSlugIndexRoute
  ProtectedOrgOrgSlugPollsNewRoute: typeof ProtectedOrgOrgSlugPollsNewRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedOrgNewRoute: ProtectedOrgNewRoute,
  ProtectedPollImportRoute: ProtectedPollImportRoute,
  ProtectedPollNewRoute: ProtectedPollNewRoute,
  ProtectedUserIdRoute: ProtectedUserIdRoute,
  ProtectedUserMeRoute: ProtectedUserMeRoute,
  ProtectedUserNewRoute: ProtectedUserNewRoute,
  ProtectedOrgIndexRoute: ProtectedOrgIndexRoute,
  ProtectedUserIndexRoute: ProtectedUserIndexRoute,
  ProtectedOrgOrgSlugInviteRoute: ProtectedOrgOrgSlugInviteRoute,
  ProtectedOrgOrgSlugMembersRoute: ProtectedOrgOrgSlugMembersRoute,
  ProtectedPollSlugUpdateRoute: ProtectedPollSlugUpdateRoute,
  ProtectedPollSlugUserResultRoute: ProtectedPollSlugUserResultRoute,
  ProtectedUserUpdateIdRoute: ProtectedUserUpdateIdRoute,
  ProtectedOrgOrgSlugIndexRoute: ProtectedOrgOrgSlugIndexRoute,
  ProtectedOrgOrgSlugPollsNewRoute: ProtectedOrgOrgSlugPollsNewRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPollGenerateQuestionsRoute: ApiPollGenerateQuestionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
